channels:
  - conda-forge
dependencies:
  - python=3.7
  - bokeh=2.0
  - numpy=1.18
  - pandas=1.0
  - scipy=1.4
  - pyyaml=5.3
  - jupyterlab=2.1
  - jupyter-server-proxy=1.3
  - librosa=0.7
  - pip
  - pip:
    - praat-parselmouth

#
#- nodejs=13
#- nbconvert=5.6
#- widgetsnbextension=3.5
#- ipykernel=5.2
#- ipywidgets=7.5
#- ipyleaflet=0.12
#- matplotlib=3.1
#- seaborn=0.9
#- traittypes=0.2.1
